server:
    mode: debug
    bind: :4869
log:
    level: debug
    formatter: text
database:
    engine: postgres
    address: 'localhost:5432'
    name: product
    username: 'root'
    password: 'root'
    maxIdleConns: 2
    maxOpenConns: 0
    connMaxLifeMinutes: 60
    logMode: true
    autoMigrate: true
redis:
    mode: single-instance
    address: localhost:6379
    password: ''
    db: 0
    master: ''
sentry:
    dsn: ''
    onlyCrashes: false
